// @ts-check
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import vercel from '@astrojs/vercel';

/**
 * astro.config.mjs — REPORTS-SEO-FOUNDATION (2026-07-07)
 *
 * LATEST CHANGE (REPORTS-SEO-FOUNDATION):
 *  - Sitemap filter now EXCLUDES ONLY `/api/*` routes. Previously excluded
 *    `/404` and `/design/*` — that is wrong per the new foundation rule
 *    ("كل صفحة تُفهرس"). Now 404 (still rendered as HTML page) and the
 *    `/design/*` system reference pages are ALL included in sitemap.xml.
 *  - `site` retained as `https://brightai.site` (confirmed by founder
 *    on 2026-07-07 — brightai.site is the live production domain, NOT
 *    www.brightaii.com which appeared in the original task brief).
 *  - Everything else from REPORTS-SEC-01 (Vercel adapter for `/api/ai/chat`)
 *    is preserved verbatim.
 *
 * PRESERVATION CONTRACT (REPORTS-SEC-01):
 *  - `output: 'static'` retained → all `.astro` pages remain prerendered HTML.
 *  - API route explicitly opts out via `export const prerender = false`
 *    → it becomes a serverless function; everything else stays static.
 *  - `site`, `trailingSlash: 'always'`, `compressHTML`, `redirects`,
 *    `vite` config unchanged.
 *
 * DEPLOYMENT NOTE:
 *  - Vercel: works out-of-the-box. `astro build` will emit
 *    `.vercel/output/functions/api/ai/chat.func/` + static `dist/`.
 *  - Render static: does NOT execute Vercel functions. To deploy on
 *    Render, either (a) swap `vercel(...)` for `node({ mode: 'standalone' })`
 *    + `npm install @astrojs/node`, or (b) migrate hosting to Vercel.
 *    This is documented in reports/2026-07-06-secret-hardening.md.
 */
export default defineConfig({
  site: 'https://brightai.site',
  output: 'static',
  trailingSlash: 'always',
  compressHTML: true,
  redirects: {
    '/report/': {
      status: 301,
      destination: '/trust/',
    },
  },
  build: {
    format: 'directory',
  },
  integrations: [
    sitemap({
      i18n: {
        defaultLocale: 'ar',
        locales: {
          ar: 'ar-SA',
          en: 'en-SA',
        },
      },
      // REPORTS-SEO-FOUNDATION (2026-07-07):
      // ONLY /api/* is excluded from the sitemap. Every other built HTML
      // page is indexable, including /404.html and /design/* system pages.
      // (500.html is generated by Render hosting as a static fallback and
      // is excluded by the Astro integration itself.)
      filter: (page) => !page.includes('/api/'),
      // @astrojs/sitemap v3 ignores status-code pages (404/500) by default.
      // REPORTS-SEO-FOUNDATION requires the 404 page to be indexable, so we
      // explicitly inject it via `customPages`. The 500 page remains
      // excluded because it's a server-error fallback (not a real route).
      customPages: [
        'https://brightai.site/404/',
      ],
      changefreq: 'weekly',
      priority: 0.7,
      lastmod: new Date(),
    }),
  ],
  adapter: vercel({
    // We rely on Astro's built-in image pipeline; do not double-process via Vercel.
    imageService: false,
    // No Vercel Web Analytics — BrightAI uses GA4 + Clarity instead.
    webAnalytics: false,
    // Exclude the legacy preview/manifest paths from edge middleware if any.
    edgeMiddleware: false,
  }),
  vite: {
    build: {
      cssMinify: true,
    },
  },
});